FROM balenalib/%%BALENA_MACHINE_NAME%%-node:latest

WORKDIR /usr/src/app

RUN install_packages wget nginx nginx-light

COPY 2048 /var/www/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]